version: "3.9"

services: 
    postgres:
        build: ./docker/postgres
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=password
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5481:5432"
        volumes:
            - ./db:/var/lib/postgresql/data/pgdata
            
    app:
        image: node:lts-alpine3.13
        command: npm run start:debug
        restart: unless-stopped
        ports: 
            - 3003:3000
            - 9229:9229
        volumes: 
            - "./packages/nestjs-backend:/app"
        environment: 
            NODE_ENV: development
            HOST: 0.0.0.0
        working_dir: /app
        depends_on: 
            - postgres

    ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        restart: unless-stopped
        hostname: localhost
        ports:
          - 2135:2135
          - 8765:8765
          - 2136:2136
        volumes:
          - ./ydb_data:/ydb_data
          - ./ydb_certs:/ydb_certs
        environment:
          - YDB_DEFAULT_LOG_LEVEL=NOTICE
          - GRPC_TLS_PORT=2135
          - GRPC_PORT=2136
          - MON_PORT=8765
