version: "3.9"

services: 
    postgres:
        build: ./docker/postgres
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=password
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5481:5432"
        volumes:
            - ./db:/var/lib/postgresql/data/pgdata
            
    app:
        image: node:lts-alpine3.13
        command: npm run start:debug
        restart: unless-stopped
        ports: 
            - 3003:3000
            - 9229:9229
        volumes: 
            - "./packages/nestjs-backend:/app"
        environment: 
            NODE_ENV: development
            HOST: 0.0.0.0
        working_dir: /app
        depends_on: 
            - postgres