name: Setup node_modules
description: Setup node_modules from a cache

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Create node_modules cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-