name: Furpage ci/cd

on: push

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: |
          yarn install
          yarn run setup



  build:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: saved-node_modules

      - run: yarn run build:legacy