name: Furpage ci/cd

on: push

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get cache
        uses: ./.github/workflows/composite/setup

      - name: Install
        run: yarn run setup

  eslint:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Get cache
        uses: ./.github/workflows/composite/setup

      - name: Run eslint
        run: yarn run eslint

  build-legacy-plugin:
    runs-on: ubuntu-20.04
    needs: 
      - setup
      - eslint
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: legacy_filter
        with:
          filters: |
            plugin_front_legacy:
              - 'packages/plugin-front-legacy/**'

      - name: Get cache
        if: ${{ steps.legacy_filter.outputs.plugin_front_legacy == 'true' }}
        uses: ./.github/workflows/composite/setup

      - name: Build Plugin
        if: ${{ steps.legacy_filter.outputs.plugin_front_legacy == 'true' }}
        run: yarn run build:legacy

      - name: Create Artifact
        if: ${{ steps.legacy_filter.outputs.plugin_front_legacy == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          path: packages/plugin-front-legacy/release