name: Furpage ci/cd

on: push

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: |
          yarn install
          yarn run setup

      - uses: actions/upload-artifact@v2
        with:
          name: saved-node_modules
          path: |
            node_modules
            packages/*/node_modules

  build:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: saved-node_modules

      - run: yarn run build:legacy