name: Furpage ci/cd

on: push

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get cache
        uses: ./.github/workflows/composite/setup

      - name: Install
        run: yarn run setup

  automatic-release:
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' && always() }}
    needs: release-legacy-plugin
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Get cache
        uses: ./.github/workflows/composite/setup

      - name: Make release
        run: |
          git config --global user.email "automatic-release@github.com"
          git config --global user.name "Automatic Release Bot"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          yarn run release

  eslint:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Get cache
        uses: ./.github/workflows/composite/setup

      - name: Run eslint
        run: yarn run eslint

  build-legacy-plugin:
    runs-on: ubuntu-20.04
    needs: 
      - setup
      - eslint
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: legacy-filter
        with:
          filters: |
            plugin-front-legacy:
              - 'packages/plugin-front-legacy/**'

      - name: Get cache
        if: ${{ steps.legacy-filter.outputs.plugin-front-legacy == 'true' }}
        uses: ./.github/workflows/composite/setup

      - name: Build Plugin
        if: ${{ steps.legacy-filter.outputs.plugin-front-legacy == 'true' }}
        run: yarn run build:legacy

      - name: Create Artifact
        if: ${{ steps.legacy-filter.outputs.plugin-front-legacy == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          path: packages/plugin-front-legacy/release

  release-legacy-plugin:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: 
      - build-legacy-plugin
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: legacy-filter
        with:
          filters: |
            plugin-front-legacy:
              - 'packages/plugin-front-legacy/**'

      - name: Get artifact
        if: ${{ steps.legacy-filter.outputs.plugin-front-legacy == 'true' }}
        uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        if: ${{ steps.legacy-filter.outputs.plugin-front-legacy == 'true' }}
        run: |
          ls -R
          echo "GITHUB_ARTIFACT=$(basename ./artifact/*.zip)" >> $GITHUB_ENV

      - name: Upload extension to the chrome store
        if: ${{ steps.legacy-filter.outputs.plugin-front-legacy == 'true' }}
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: ./artifact/${{ env.GITHUB_ARTIFACT }}
          app-id: ${{ secrets.APP_ID }}
          publish: true
