name: Furpage ci/cd

on: push

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: .github/workflows/composite/setup
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 16

      # - uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     path: |
      #       node_modules
      #       */*/node_modules
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: Install
        run: yarn run setup

  build:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - uses: .github/workflows/composite/setup
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 16

      # - uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     path: |
      #       node_modules
      #       */*/node_modules
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-    

      - name: Build Plugin
        run: yarn run build:legacy

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          path: packages/plugin-front-legacy/release